# Generated by Django 4.2.4 on 2025-05-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='start_time',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.category'),
        ),
        migrations.AddField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
